#!/bin/bash

# Create all directories
mkdir -p .github/workflows
mkdir -p .playwright-mcp
mkdir -p app/api/auth/wallet
mkdir -p app/api/sessions/[id]
mkdir -p app/api/transcription
mkdir -p app/dashboard
mkdir -p app/features
mkdir -p app/help
mkdir -p app/session/[id]
mkdir -p base_blockchain_setup
mkdir -p components/ui
mkdir -p contracts/contracts
mkdir -p contracts/deployments
mkdir -p contracts/scripts
mkdir -p contracts/test
mkdir -p database/lib
mkdir -p database/migrations
mkdir -p database/schemas
mkdir -p database/scripts
mkdir -p fixe_auth
mkdir -p fixe_session_management
mkdir -p fixe_transcription
mkdir -p hooks
mkdir -p lib/analytics
mkdir -p lib/assembly-ai
mkdir -p lib/types
mkdir -p lib/validation
mkdir -p public
mkdir -p scripts
mkdir -p services/transcription/api
mkdir -p services/transcription/lib
mkdir -p transcription_template/api
mkdir -p transcription_template/lib
mkdir -p Template/app/api/auth/wallet
mkdir -p Template/app/api/sessions
mkdir -p Template/app/api/transcription
mkdir -p Template/app/dashboard
mkdir -p Template/app/features
mkdir -p Template/app/fonts
mkdir -p Template/app/help
mkdir -p Template/app/session/[id]
mkdir -p Template/artifacts/build-info
mkdir -p Template/artifacts/contracts/SessionPool.sol
mkdir -p Template/artifacts/contracts/SessionPoolFactory.sol
mkdir -p Template/cache
mkdir -p Template/components/ui
mkdir -p Template/contracts
mkdir -p Template/hooks
mkdir -p Template/lib
mkdir -p Template/public
mkdir -p Template/scripts
mkdir -p Template/services/transcription/api
mkdir -p Template/services/transcription/lib
mkdir -p Template/styles
mkdir -p Template/typechain-types/factories

# Move files
# Root files
mv .github/workflows/Package-lock.yml .github/workflows/
mv .github/workflows/newmain.yml .github/workflows/
mv .gitignore ./
mv .npmrc ./
mv .playwright-mcp/login-page-wallet-button.png .playwright-mcp/
mv AI_Aid.md ./
mv Database_Schema/Transcription_table database/schemas/
mv Database_Schema/Transcription_table.sql database/schemas/
mv Database_Schema/auth_enhancements.sql database/schemas/
mv Database_Schema/profiles_table database/schemas/
mv Database_Schema/profiles_table.sql database/schemas/
mv Database_Schema/session_enhancements_v1.sql database/schemas/
mv Database_Schema/session_table database/schemas/
mv Database_Schema/session_table.sql database/schemas/
mv Database_Schema/sessions_participants_table database/schemas/
mv Database_Schema/sessions_participants_table.sql database/schemas/
mv Database_Schema/transcription_enhancements_v1.sql database/schemas/
mv How\ to\ fix\ \ dependency\ issues.md ./
mv Instructions\ for\ Gossiper.md ./
mv Non-Technical\ User\ Flow.md ./
mv PR_DOCUMENTATION.md ./
mv Package-lock.txttxt ./
mv README.md ./
mv Technical\ User\ Flow.md ./
mv Template/HACKATHON_SUBMISSION.md Template/
mv Template/MIGRATION_COMPLETE.md Template/
mv Template/PRODUCT_REQUIREMENTS_DOCUMENT.md Template/
mv Template/README.md Template/
mv Template/README_AUTH.md Template/
mv Template/SETUP_INSTRUCTIONS.md Template/
mv Template/SMART_CONTRACT_IMPLEMENTATION.md Template/
mv Template/WALLET_AUTH_MIGRATION.md Template/
mv Template/app/about/page.tsx Template/app/about/
mv Template/app/api/auth/me/route.ts Template/app/api/auth/me/
mv Template/app/api/auth/signin/route.ts Template/app/api/auth/
mv Template/app/api/auth/signout/route.ts Template/app/api/auth/
mv Template/app/api/auth/signup/route.ts Template/app/api/auth/
mv Template/app/api/auth/wallet/connect/route.ts Template/app/api/auth/wallet/
mv Template/app/api/auth/wallet/disconnect/route.ts Template/app/api/auth/wallet/
mv Template/app/api/sessions/[id]/route.ts Template/app/api/sessions/
mv Template/app/api/sessions/create/route.ts Template/app/api/sessions/
mv Template/app/api/sessions/join/route.ts Template/app/api/sessions/
mv Template/app/api/sessions/my-sessions/route.ts Template/app/api/sessions/
mv Template/app/api/sessions/validate-code/route.ts Template/app/api/sessions/
mv Template/app/api/transcription/callback/route.ts Template/app/api/transcription/
mv Template/app/api/transcription/stream/route.ts Template/app/api/transcription/
mv Template/app/api/transcription/transcribe/route.ts Template/app/api/transcription/
mv Template/app/api/transcription/webhook/route.ts Template/app/api/transcription/
mv Template/app/careers/page.tsx Template/app/
mv Template/app/contact/page.tsx Template/app/
mv Template/app/create-session/page.tsx Template/app/
mv Template/app/dashboard/loading.tsx Template/app/dashboard/
mv Template/app/dashboard/page.tsx Template/app/dashboard/
mv Template/app/features/loading.tsx Template/app/features/
mv Template/app/features/page.tsx Template/app/features/
mv Template/app/fonts/Nohemi-Black.woff2 Template/app/fonts/
mv Template/app/fonts/Nohemi-Bold.woff2 Template/app/fonts/
mv Template/app/fonts/Nohemi-ExtraBold.woff2 Template/app/fonts/
mv Template/app/fonts/Nohemi-ExtraLight.woff2 Template/app/fonts/
mv Template/app/fonts/Nohemi-Light.woff2 Template/app/fonts/
mv Template/app/fonts/Nohemi-Medium.woff2 Template/app/fonts/
mv Template/app/fonts/Nohemi-Regular.woff2 Template/app/fonts/
mv Template/app/fonts/Nohemi-SemiBold.woff2 Template/app/fonts/
mv Template/app/fonts/Nohemi-Thin.woff2 Template/app/fonts/
mv Template/app/forgot-password/page.tsx Template/app/
mv Template/app/globals.css Template/app/
mv Template/app/help/loading.tsx Template/app/help/
mv Template/app/help/page.tsx Template/app/help/
mv Template/app/join-session/page.tsx Template/app/
mv Template/app/layout.tsx Template/app/
mv Template/app/login/page.tsx Template/app/
mv Template/app/page.tsx Template/app/
mv Template/app/pricing/page.tsx Template/app/
mv Template/app/privacy/page.tsx Template/app/
mv Template/app/session/[id]/loading.tsx Template/app/session/[id]/
mv Template/app/session/[id]/page.tsx Template/app/session/[id]/
mv Template/app/signup/page.tsx Template/app/
mv Template/app/terms/page.tsx Template/app/
mv Template/artifacts/build-info/1b3849490922276a1ad65225d86b25c0.json Template/artifacts/build-info/
mv Template/artifacts/contracts/SessionPool.sol/SessionPool.dbg.json Template/artifacts/contracts/SessionPool.sol/
mv Template/artifacts/contracts/SessionPool.sol/SessionPool.json Template/artifacts/contracts/SessionPool.sol/
mv Template/artifacts/contracts/SessionPoolFactory.sol/SessionPoolFactory.dbg.json Template/artifacts/contracts/SessionPoolFactory.sol/
mv Template/artifacts/contracts/SessionPoolFactory.sol/SessionPoolFactory.json Template/artifacts/contracts/SessionPoolFactory.sol/
mv Template/cache/solidity-files-cache.json Template/cache/
mv Template/components.json Template/
mv Template/components/accessibility-provider.tsx Template/components/
mv Template/components/accessibility-toolbar.tsx Template/components/
mv Template/components/caption-display.tsx Template/components/
mv Template/components/footer.tsx Template/components/
mv Template/components/lecturer-transcription-display.tsx Template/components/
mv Template/components/live-announcer.tsx Template/components/
mv Template/components/main-navigation.tsx Template/components/
mv Template/components/onchain-provider.tsx Template/components/
mv Template/components/payment-modal.tsx Template/components/
mv Template/components/realtime-transcription-display.tsx Template/components/
mv Template/components/session-card.tsx Template/components/
mv Template/components/skip-navigation.tsx Template/components/
mv Template/components/theme-provider.tsx Template/components/
mv Template/components/transcription-display.tsx Template/components/
mv Template/components/ui/alert.tsx Template/components/ui/
mv Template/components/ui/badge.tsx Template/components/ui/
mv Template/components/ui/button.tsx Template/components/ui/
mv Template/components/ui/card.tsx Template/components/ui/
mv Template/components/ui/checkbox.tsx Template/components/ui/
mv Template/components/ui/dialog.tsx Template/components/ui/
mv Template/components/ui/dropdown-menu.tsx Template/components/ui/
mv Template/components/ui/input.tsx Template/components/ui/
mv Template/components/ui/label.tsx Template/components/ui/
mv Template/components/ui/progress.tsx Template/components/ui/
mv Template/components/ui/select.tsx Template/components/ui/
mv Template/components/ui/separator.tsx Template/components/ui/
mv Template/components/ui/sheet.tsx Template/components/ui/
mv Template/components/ui/switch.tsx Template/components/ui/
mv Template/components/ui/tabs.tsx Template/components/ui/
mv Template/components/ui/textarea.tsx Template/components/ui/
mv Template/components/wagmi-provider.tsx Template/components/
mv Template/components/wallet-connect-button.tsx Template/components/
mv Template/contracts/SessionPool.sol Template/contracts/
mv Template/contracts/SessionPoolFactory.sol Template/contracts/
mv Template/hardhat.config.ts Template/
mv Template/hooks/use-auth.tsx Template/hooks/
mv Template/hooks/use-captions.ts Template/hooks/
mv Template/hooks/use-realtime-transcription.ts Template/hooks/
mv Template/hooks/use-session-pool.ts Template/hooks/
mv Template/hooks/use-transcription.ts Template/hooks/
mv Template/hooks/use-wallet.ts Template/hooks/
mv Template/hooks/use-websocket.ts Template/hooks/
mv Template/lib/auth-schema.sql Template/lib/
mv Template/lib/auth.ts Template/lib/
mv Template/lib/contracts.ts Template/lib/
mv Template/lib/db.ts Template/lib/
mv Template/lib/sessions-schema.sql Template/lib/
mv Template/lib/types.ts Template/lib/
mv Template/lib/utils.ts Template/lib/
mv Template/lib/wagmi-config.ts Template/lib/
mv Template/next.config.mjs Template/
mv Template/package-lock.json Template/
mv Template/package.json Template/
mv Template/playwright-mcp-config.json Template/
mv Template/pnpm-lock.yaml Template/
mv Template/postcss.config.mjs Template/
mv Template/public/arixe.jpeg Template/public/
mv Template/public/goodness.jpeg Template/public/
mv Template/public/gossiper-features-page.png Template/public/
mv Template/public/gossiper-homepage.png Template/public/
mv Template/public/gossiper-join-session-wallet-required.png Template/public/
mv Template/public/gossiper-logo-white.png Template/public/
mv Template/public/gossiper-logo.jpeg Template/public/
mv Template/public/gossiper-wallet-login.png Template/public/
mv Template/public/gwen.png Template/public/
mv Template/public/melody.jpeg Template/public/
mv Template/public/oghenetega.jpg Template/public/
mv Template/public/placeholder-user.jpg Template/public/
mv Template/public/placeholder.jpg Template/public/
mv Template/public/placeholder.svg Template/public/
mv Template/public/professional-headshot-of-dr--adebayo-ogundimu.jpg Template/public/
mv Template/public/professional-headshot-of-michael-rodriguez.jpg Template/public/
mv Template/public/professional-headshot-of-sarah-chen.jpg Template/public/
mv Template/public/victory.JPG Template/public/
mv Template/scripts/deploy.ts Template/scripts/
mv Template/scripts/init-db.ts Template/scripts/
mv Template/scripts/test-connection.ts Template/scripts/
mv Template/scripts/test-db.ts Template/scripts/
mv Template/services/transcription/Instructions\ for\ Gossiper.md Template/services/transcription/
mv Template/services/transcription/api/transcribe.ts Template/services/transcription/api/
mv Template/services/transcription/api/webhook.ts Template/services/transcription/api/
mv Template/services/transcription/lib/assemblyai.ts Template/services/transcription/lib/
mv Template/services/transcription/lib/config.ts Template/services/transcription/lib/
mv Template/services/transcription/lib/types.ts Template/services/transcription/lib/
mv Template/services/transcription/package.json Template/services/transcription/
mv Template/services/transcription/tsconfig.json Template/services/transcription/
mv Template/services/transcription/vercel.json Template/services/transcription/
mv Template/styles/globals.css Template/styles/
mv Template/tailwind.config.js Template/
mv Template/tsconfig.json Template/
mv Template/typechain-types/SessionPool.ts Template/typechain-types/
mv Template/typechain-types/SessionPoolFactory.ts Template/typechain-types/
mv Template/typechain-types/common.ts Template/typechain-types/
mv Template/typechain-types/factories/SessionPoolFactory__factory.ts Template/typechain-types/factories/
mv Template/typechain-types/factories/SessionPool__factory.ts Template/typechain-types/factories/
mv Template/typechain-types/factories/index.ts Template/typechain-types/factories/
mv Template/typechain-types/hardhat.d.ts Template/typechain-types/
mv Template/typechain-types/index.ts Template/typechain-types/
mv WALLET_AUTH_SETUP.md ./
mv app/about/page.tsx app/about/
mv app/api/auth/me/route.ts app/api/auth/me/
mv app/api/auth/wallet/signin/route.ts app/api/auth/wallet/
mv app/api/auth/wallet/signup/route.ts app/api/auth/wallet/
mv app/api/auth/wallet/verify/route.ts app/api/auth/wallet/
mv app/api/sessions/[id]/participants/route.ts app/api/sessions/[id]/
mv app/api/sessions/[id]/route.ts app/api/sessions/[id]/
mv app/api/sessions/create/route.ts app/api/sessions/
mv app/api/sessions/join/route.ts app/api/sessions/
mv app/api/transcription/callback/route.ts app/api/transcription/
mv app/api/transcription/transcribe/route.ts app/api/transcription/
mv app/contact/page.tsx app/
mv app/create-session/page.tsx app/
mv app/dashboard/loading.tsx app/dashboard/
mv app/dashboard/page.tsx app/dashboard/
mv app/features/loading.tsx app/features/
mv app/features/page.tsx app/features/
mv app/forgot-password/page.tsx app/
mv app/globals.css app/
mv app/help/loading.tsx app/help/
mv app/help/page.tsx app/help/
mv app/join-session/page.tsx app/
mv app/layout.tsx app/
mv app/login/page.tsx app/
mv app/page.tsx app/
mv app/pricing/page.tsx app/
mv app/privacy/page.tsx app/
mv app/session/[id]/loading.tsx app/session/[id]/
mv app/session/[id]/page.tsx app/session/[id]/
mv app/session/[id]/session-page.txt app/session/[id]/
mv app/signup/page.tsx app/
mv app/terms/page.tsx app/
mv base_blockchain_setup/BASE_BLOCKCHAIN_INDEX.md base_blockchain_setup/
mv base_blockchain_setup/BASE_INTEGRATION_GUIDE.md base_blockchain_setup/
mv base_blockchain_setup/BASE_PAYMENT_SUMMARY.md base_blockchain_setup/
mv base_blockchain_setup/DEPLOYMENT_CHECKLIST.md base_blockchain_setup/
mv base_blockchain_setup/PAYMENT_FLOW.md base_blockchain_setup/
mv base_blockchain_setup/QUICK_START.md base_blockchain_setup/
mv components.json components/
mv components/accessibility-provider.tsx components/
mv components/accessibility-toolbar.tsx components/
mv components/auth-guard.tsx components/
mv components/caption-display.tsx components/
mv components/live-announcer.tsx components/
mv components/main-navigation.tsx components/
mv components/payment-modal.tsx components/
mv components/realtime-transcription-display.tsx components/
mv components/session-card.tsx components/
mv components/skip-navigation.tsx components/
mv components/solana-wallet-provider.tsx components/
mv components/theme-provider.tsx components/
mv components/transcription-display.tsx components/
mv components/ui/accordion.tsx components/ui/
mv components/ui/alert-dialog.tsx components/ui/
mv components/ui/alert.tsx components/ui/
mv components/ui/aspect-ratio.tsx components/ui/
mv components/ui/avatar.tsx components/ui/
mv components/ui/badge.tsx components/ui/
mv components/ui/breadcrumb.tsx components/ui/
mv components/ui/button-group.tsx components/ui/
mv components/ui/button.tsx components/ui/
mv components/ui/calendar.tsx components/ui/
mv components/ui/card.tsx components/ui/
mv components/ui/carousel.tsx components/ui/
mv components/ui/chart.tsx components/ui/
mv components/ui/checkbox.tsx components/ui/
mv components/ui/collapsible.tsx components/ui/
mv components/ui/command.tsx components/ui/
mv components/ui/context-menu.tsx components/ui/
mv components/ui/dialog.tsx components/ui/
mv components/ui/drawer.tsx components/ui/
mv components/ui/dropdown-menu.tsx components/ui/
mv components/ui/empty.tsx components/ui/
mv components/ui/field.tsx components/ui/
mv components/ui/form.tsx components/ui/
mv components/ui/hover-card.tsx components/ui/
mv components/ui/input-group.tsx components/ui/
mv components/ui/input-otp.tsx components/ui/
mv components/ui/input.tsx components/ui/
mv components/ui/item.tsx components/ui/
mv components/ui/kbd.tsx components/ui/
mv components/ui/label.tsx components/ui/
mv components/ui/menubar.tsx components/ui/
mv components/ui/navigation-menu.tsx components/ui/
mv components/ui/pagination.tsx components/ui/
mv components/ui/popover.tsx components/ui/
mv components/ui/progress.tsx components/ui/
mv components/ui/radio-group.tsx components/ui/
mv components/ui/resizable.tsx components/ui/
mv components/ui/scroll-area.tsx components/ui/
mv components/ui/select.tsx components/ui/
mv components/ui/separator.tsx components/ui/
mv components/ui/sheet.tsx components/ui/
mv components/ui/sidebar.tsx components/ui/
mv components/ui/skeleton.tsx components/ui/
mv components/ui/slider.tsx components/ui/
mv components/ui/sonner.tsx components/ui/
mv components/ui/spinner.tsx components/ui/
mv components/ui/switch.tsx components/ui/
mv components/ui/table.tsx components/ui/
mv components/ui/tabs.tsx components/ui/
mv components/ui/textarea.tsx components/ui/
mv components/ui/toast.tsx components/ui/
mv components/ui/toaster.tsx components/ui/
mv components/ui/toggle-group.tsx components/ui/
mv components/ui/toggle.tsx components/ui/
mv components/ui/tooltip.tsx components/ui/
mv components/ui/use-mobile.tsx components/ui/
mv components/ui/use-toast.ts components/ui/
mv components/wallet-multi-button.tsx components/
mv contracts/.gitignore contracts/
mv contracts/README.md contracts/
mv contracts/SessionPaymentABI.json contracts/
mv contracts/contracts/SessionPayment.sol contracts/contracts/
mv contracts/deployments/.gitkeep contracts/deployments/
mv contracts/hardhat.config.js contracts/
mv contracts/package-lock.json contracts/
mv contracts/package.json contracts/
mv contracts/scripts/deploy.js contracts/scripts/
mv contracts/test/SessionPayment.test.js contracts/test/
mv curl1\ codes.md ./
mv curl_test.txt ./
mv env_updated.txt ./
mv fixe_auth/AUTH_IMPROVEMENT_PROPOSAL.md fixe_auth/
mv fixe_auth/Auth-fixes_progress_2.md fixe_auth/
mv fixe_auth/Auth_signup_signin_redirect.md fixe_auth/
mv fixe_auth/last-auth_improvements_progress.md fixe_auth/
mv fixe_auth/signup_signin_redirect.md fixe_auth/
mv fixe_session_management/SESSION_MANAGEMENT_AND_USER_ROLE_IMPROVEMENT_PROPOSAL.md fixe_session_management/
mv fixe_session_management/Session_logic_and_flow.md fixe_session_management/
mv fixe_session_management/Session_management_progress.md fixe_session_management/
mv fixe_transcription/TRANSCRIPTION_IMPROVEMENT_PROPOSAL.md fixe_transcription/
mv fixe_transcription/Transcription-flow.md fixe_transcription/
mv fixe_transcription/Transcription_update_progress.md fixe_transcription/
mv hooks/use-auth-legacy.ts hooks/
mv hooks/use-auth.tsx hooks/
mv hooks/use-base.ts hooks/
mv hooks/use-captions.ts hooks/
mv hooks/use-mobile.ts hooks/
mv hooks/use-realtime-transcriptions.ts hooks/
mv hooks/use-solana.ts hooks/
mv hooks/use-toast.ts hooks/
mv hooks/use-transcription.ts hooks/
mv hooks/use-websocket.ts hooks/
mv lib/analytics/session-analytics.ts lib/analytics/
mv lib/analytics/transcription-analytics.ts lib/analytics/
mv lib/assembly-ai/fetch-transcript.ts lib/assembly-ai/
mv lib/auth-error-handler.ts lib/
mv lib/auth-security.ts lib/
mv lib/auth-utils.ts lib/
mv lib/auth-validation.ts lib/
mv lib/session-service-client.ts lib/
mv lib/session-service-server.ts lib/
mv lib/supabase-auth.ts lib/
mv lib/supabase-client.ts lib/
mv lib/supabase-server.ts lib/
mv lib/types.ts lib/
mv lib/types/session.ts lib/types/
mv lib/types/transcription.ts lib/types/
mv lib/utils.ts lib/
mv lib/validation/session-validation.ts lib/validation/
mv lib/validation/transcription-validation.ts lib/validation/
mv lib/validation/webhook-validation.ts lib/validation/
mv middleware-future.txt ./
mv middleware-old.txt ./
mv middleware.ts ./
mv next.config.mjs ./
mv package-lock.json ./
mv package.json ./
mv package.rar ./
mv postcss.config.js ./
mv postcss_config_fixes.md ./
mv public/Arixe.jpg public/
mv public/Hikaru.jpg public/
mv public/Victory.jpg public/
mv public/gossiper-logo-white.png public/
mv public/gossiper-logo.jpeg public/
mv public/melody.jpg public/
mv public/placeholder-logo.png public/
mv public/placeholder-logo.svg public/
mv public/placeholder-user.jpg public/
mv public/placeholder.jpg public/
mv public/placeholder.svg public/
mv public/professional-headshot-of-dr--adebayo-ogundimu.jpg public/
mv public/professional-headshot-of-michael-rodriguez.jpg public/
mv public/professional-headshot-of-sarah-chen.jpg public/
mv scripts/session_enhancements_v1.sql database/scripts/
mv scripts/transcription_enhancements_v1.sql database/scripts/
mv services/transcription/api/transcribe.ts services/transcription/api/
mv services/transcription/api/webhook.ts services/transcription/api/
mv services/transcription/lib/assemblyai.ts services/transcription/lib/
mv services/transcription/lib/config.ts services/transcription/lib/
mv services/transcription/lib/types.ts services/transcription/lib/
mv services/transcription/package.json services/transcription/
mv services/transcription/tsconfig.json services/transcription/
mv services/transcription/vercel.json services/transcription/
mv supabase-migrations/001_wallet_auth.sql database/migrations/
mv tailwind.config.txt ./
mv transcription_template/Instructions\ for\ Gossiper.md transcription_template/
mv transcription_template/api/transcribe.ts transcription_template/api/
mv transcription_template/api/webhook.ts transcription_template/api/
mv transcription_template/lib/assemblyai.ts transcription_template/lib/
mv transcription_template/lib/config.ts transcription_template/lib/
mv transcription_template/lib/types.ts transcription_template/lib/
mv transcription_template/package.json transcription_template/
mv transcription_template/tsconfig.json transcription_template/
mv transcription_template/vercel.json transcription_template/
mv tsconfig.json ./
mv vercel.json ./

echo "Reorganization complete. Check for errors and update imports."
